### ISSUE TITLE
TICCL-unk runtime error

### ISSUE THREAD

**Issue by pdekker12** [LanguageMachines/ticcltools#18]
I installed the latest version of LaMachine, which contains the latest version of ticcltools.

I uploaded a tif file through the CLAM API, to process it through the whole PICCL pipeline. Before, this worked, for the same file. Now, I get the following error:

```
Caused by:
  Process `ticclunk (1)` terminated with an error exit status (134)

Command executed:

  set +u
  if [ ! -z "" ]; then
      source /bin/activate
  fi
  set -u
  
  TICCL-unk --background "lexicon.lst" --artifrq 10000000 "corpus.wordfreqlist.tsv"

Command exit status:
  134

Command output:
  (empty)

Command error:
  terminate called after throwing an instance of 'std::runtime_error'
    what():  creating UniFilter: default_filter failed
  error in rules, line=-1 at postion: -1
  .command.sh: line 8: 12503 Aborted                 TICCL-unk --background "lexicon.lst" --artifrq 10000000 "corpus.wordfreqlist.tsv"

Work dir:
  /vol1/lamachine/piccl.clam/projects/anonymous/test001/work/99/5dcdd7247fcfb28c3f5224380e4b0c

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details
```

@proycon I added the issue here, but may also be PICCL-related?

**Comment by kosloot** [comment]
Hmm
never seen this before. Which version of ICU do you have?
@proycon does 'make check' in ticcutils work? as it tests this functionality.

**Comment by proycon** [comment]
``make check`` runs fine for me for ticcutils (you do mean ticcutils and not ticcltools right?)

**Comment by pdekker12** [comment]
This is my `icu` version: version 50.1.2 release 15.el7

**Comment by kosloot** [comment]
yeah in the ticcutils directory.
 @pdekker12 can you try 'make check' too? I'm not sure where exactly this directory is located in LaMachine
iCU 50 is quite old, but I use the icu::Transliterator class, which already there since version 20.
puzzling

**Comment by pdekker12** [comment]
`make check` for ticcutils:
```
Making check in src
make[1]: Map '/vol1/lamachine/src/ticcutils/src' wordt binnengegaan
make  runtest testlogstream
make[2]: Map '/vol1/lamachine/src/ticcutils/src' wordt binnengegaan
g++ -DHAVE_CONFIG_H -I. -I..  -I../include -I/usr/include -I/usr/include -I/vol1/lamachine/include -g -std=c++11 -O3 -W -Wall -pedantic -D U_USING_ICU_NAMESPACE=1 -fopenmp -pthread -I/usr/include/libxml2     -MT runtest.o -MD -MP -MF .deps/runtest.Tpo -c -o runtest.o runtest.cxx
mv -f .deps/runtest.Tpo .deps/runtest.Po
/bin/sh ../libtool  --tag=CXX   --mode=link g++ -g -std=c++11 -O3 -W -Wall -pedantic -D U_USING_ICU_NAMESPACE=1 -fopenmp -pthread -I/usr/include/libxml2      -L/usr/lib -L/usr/lib -L/vol1/lamachine/lib64 -o runtest runtest.o libticcutils.la -licuio -licui18n -licuuc -licudata    -lz  -lbz2 -ltar -lboost_regex -lxml2  
libtool: link: g++ -g -std=c++11 -O3 -W -Wall -pedantic -D U_USING_ICU_NAMESPACE=1 -fopenmp -pthread -I/usr/include/libxml2 -o .libs/runtest runtest.o  -L/usr/lib -L/vol1/lamachine/lib64 ./.libs/libticcutils.so -licuio -licui18n -licuuc -licudata -lz -lbz2 -ltar -lboost_regex -lxml2 -pthread -fopenmp -Wl,-rpath -Wl,/vol1/lamachine/lib
g++ -DHAVE_CONFIG_H -I. -I..  -I../include -I/usr/include -I/usr/include -I/vol1/lamachine/include -g -std=c++11 -O3 -W -Wall -pedantic -D U_USING_ICU_NAMESPACE=1 -fopenmp -pthread -I/usr/include/libxml2     -MT testlogstream.o -MD -MP -MF .deps/testlogstream.Tpo -c -o testlogstream.o testlogstream.cxx
mv -f .deps/testlogstream.Tpo .deps/testlogstream.Po
/bin/sh ../libtool  --tag=CXX   --mode=link g++ -g -std=c++11 -O3 -W -Wall -pedantic -D U_USING_ICU_NAMESPACE=1 -fopenmp -pthread -I/usr/include/libxml2      -L/usr/lib -L/usr/lib -L/vol1/lamachine/lib64 -o testlogstream testlogstream.o libticcutils.la -licuio -licui18n -licuuc -licudata    -lz  -lbz2 -ltar -lboost_regex -lxml2  
libtool: link: g++ -g -std=c++11 -O3 -W -Wall -pedantic -D U_USING_ICU_NAMESPACE=1 -fopenmp -pthread -I/usr/include/libxml2 -o .libs/testlogstream testlogstream.o  -L/usr/lib -L/vol1/lamachine/lib64 ./.libs/libticcutils.so -licuio -licui18n -licuuc -licudata -lz -lbz2 -ltar -lboost_regex -lxml2 -pthread -fopenmp -Wl,-rpath -Wl,/vol1/lamachine/lib
make[2]: Map '/vol1/lamachine/src/ticcutils/src' wordt verlaten
make  check-TESTS
make[2]: Map '/vol1/lamachine/src/ticcutils/src' wordt binnengegaan
make[3]: Map '/vol1/lamachine/src/ticcutils/src' wordt binnengegaan
PASS: tst.sh
make[4]: Map '/vol1/lamachine/src/ticcutils/src' wordt binnengegaan
make[4]: Er hoeft niets gedaan te worden voor 'all'.
make[4]: Map '/vol1/lamachine/src/ticcutils/src' wordt verlaten
============================================================================
Testsuite summary for ticcutils 0.19
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[3]: Map '/vol1/lamachine/src/ticcutils/src' wordt verlaten
make[2]: Map '/vol1/lamachine/src/ticcutils/src' wordt verlaten
make[1]: Map '/vol1/lamachine/src/ticcutils/src' wordt verlaten
Making check in include
make[1]: Map '/vol1/lamachine/src/ticcutils/include' wordt binnengegaan
Making check in ticcutils
make[2]: Map '/vol1/lamachine/src/ticcutils/include/ticcutils' wordt binnengegaan
make[2]: Er hoeft niets gedaan te worden voor 'check'.
make[2]: Map '/vol1/lamachine/src/ticcutils/include/ticcutils' wordt verlaten
make[2]: Map '/vol1/lamachine/src/ticcutils/include' wordt binnengegaan
make[2]: Er hoeft niets gedaan te worden voor 'check-am'.
make[2]: Map '/vol1/lamachine/src/ticcutils/include' wordt verlaten
make[1]: Map '/vol1/lamachine/src/ticcutils/include' wordt verlaten
Making check in docs
make[1]: Map '/vol1/lamachine/src/ticcutils/docs' wordt binnengegaan
make[1]: Er hoeft niets gedaan te worden voor 'check'.
make[1]: Map '/vol1/lamachine/src/ticcutils/docs' wordt verlaten
Making check in m4
make[1]: Map '/vol1/lamachine/src/ticcutils/m4' wordt binnengegaan
make[1]: Er hoeft niets gedaan te worden voor 'check'.
make[1]: Map '/vol1/lamachine/src/ticcutils/m4' wordt verlaten
Making check in tests
make[1]: Map '/vol1/lamachine/src/ticcutils/tests' wordt binnengegaan
Making check in sub1
make[2]: Map '/vol1/lamachine/src/ticcutils/tests/sub1' wordt binnengegaan
make[2]: Er hoeft niets gedaan te worden voor 'check'.
make[2]: Map '/vol1/lamachine/src/ticcutils/tests/sub1' wordt verlaten
make[2]: Map '/vol1/lamachine/src/ticcutils/tests' wordt binnengegaan
make[2]: Er hoeft niets gedaan te worden voor 'check-am'.
make[2]: Map '/vol1/lamachine/src/ticcutils/tests' wordt verlaten
make[1]: Map '/vol1/lamachine/src/ticcutils/tests' wordt verlaten
make[1]: Map '/vol1/lamachine/src/ticcutils' wordt binnengegaan
make[1]: Map '/vol1/lamachine/src/ticcutils' wordt verlaten
```

`make check` for `ticcltools`:
```
Making check in include
make[1]: Map '/vol1/lamachine/src/ticcltools/include' wordt binnengegaan
Making check in ticcl
make[2]: Map '/vol1/lamachine/src/ticcltools/include/ticcl' wordt binnengegaan
make[2]: Er hoeft niets gedaan te worden voor 'check'.
make[2]: Map '/vol1/lamachine/src/ticcltools/include/ticcl' wordt verlaten
make[2]: Map '/vol1/lamachine/src/ticcltools/include' wordt binnengegaan
make[2]: Er hoeft niets gedaan te worden voor 'check-am'.
make[2]: Map '/vol1/lamachine/src/ticcltools/include' wordt verlaten
make[1]: Map '/vol1/lamachine/src/ticcltools/include' wordt verlaten
Making check in src
make[1]: Map '/vol1/lamachine/src/ticcltools/src' wordt binnengegaan
make[1]: Er hoeft niets gedaan te worden voor 'check'.
make[1]: Map '/vol1/lamachine/src/ticcltools/src' wordt verlaten
Making check in m4
make[1]: Map '/vol1/lamachine/src/ticcltools/m4' wordt binnengegaan
make[1]: Er hoeft niets gedaan te worden voor 'check'.
make[1]: Map '/vol1/lamachine/src/ticcltools/m4' wordt verlaten
Making check in docs
make[1]: Map '/vol1/lamachine/src/ticcltools/docs' wordt binnengegaan
make[1]: Er hoeft niets gedaan te worden voor 'check'.
make[1]: Map '/vol1/lamachine/src/ticcltools/docs' wordt verlaten
make[1]: Map '/vol1/lamachine/src/ticcltools' wordt binnengegaan
make[1]: Map '/vol1/lamachine/src/ticcltools' wordt verlaten
```

**Comment by pdekker12** [comment]
I am testing on different servers, so not 100% sure, but it seems that this problems only occurs when using the CLAM API. TICCL on the command line (different server, same LaMachine version) finished without errors. I am still running the webservice, to see what that does.

**Comment by proycon** [comment]
hmm, that would be very puzzling.. but I have a slight hunch what could perhaps be wrong; perhaps the CLAM service runs under a different locale than when you run it yourself? And ICU gets confused about that? I remember having seen a default ``C`` locale on CentOS before, instead of a proper UTF-8 one, which caused weird behaviour in some cases.

**Comment by pdekker12** [comment]
I tried to check my locale:
```
$ localectl status
   System Locale: LANG=nl_NL.UTF-8
       VC Keymap: us-euro
      X11 Layout: us
     X11 Variant: euro
```

**Comment by kosloot** [comment]
Hmm
we always use the locale:
System Locale: LANG=en_US.UTF-8

Maybe this explains it?
Seems odd, but.... maybe @proycon already fixed it...


that 'make check' was on the dutch variant, and succeeds.  I assume.
So what locale does CentOs use?

**Comment by pdekker12** [comment]
The last `localectl` output I posted, was from the CentOS server. Or do you mean something different?

**Comment by kosloot** [comment]
I can reproduce the crash wilt LC_ALL=C
```
ticcutils$ LC_ALL=C make check
```
fails miserably

**Comment by proycon** [comment]
Ok, so my hunch was right and my fix in PICCL should hopefully fix it by explicitly setting the locale from the CLAM wrapper script for PICCL. Hold on, I'll test and then release it.

**Comment by pdekker12** [comment]
I can report (what would be expected) that the error also occurs in the CLAM webinterface. This makes the problem more urgent. Good to hear your fix seems to work, I will test it once it is ready.

**Comment by proycon** [comment]
New PICCL is released (v0.6.1) with the fix.

**Comment by pdekker12** [comment]
Unfortunately, the same error still occurs after the fix :(

**Comment by pdekker12** [comment]
I tried to change the system locale with:
```
localectl set-locale LANG=en_US.utf8
```
and run again, but the error occurred again.

We would like to install a production server tomorrow. I hope some fix for the problem is possible. Alternatively, since this problem seems to be introduced by the new features added to `ticcltools`, maybe `ticcltools` can be reverted to the state of the previous release.

**Comment by martinreynaert** [comment]
Beste Peter,

Dank voor de goede zorgen!

Maarten is er momenteel niet, vrees ik.

Groet,

Martin

**Comment by proycon** [comment]
Sorry, I was away for a bit. The problem is more of an environment problem (wrong locale) than an inherent problem in ``ticcltools``. But it seems my PICCL fix didn't do the job? What does the ``error.log`` say regarding the locale when you enable the new debug option from the PICCL CLAM interface?

**Comment by proycon** [comment]
(note that I just released just another PICCL bugfix release because the debug mode had a problem)

**Comment by pdekker12** [comment]
I tested the latest release, unfortunately the error still occurs. How can I enable the debug mode?

**Comment by proycon** [comment]
In the webinterface there is a debug option

**Comment by pdekker12** [comment]
I cannot find it, where can I find it exactly?

**Comment by proycon** [comment]
At the bottom of all the parameters, but if it's not there then something must have failed in the update. I assume you updated all of LaMachine?

**Comment by proycon** [comment]
(also make sure to restart the webservices using ``lamachine-start-webserver``)

**Comment by pdekker12** [comment]
It is not at the bottom of the parameters, even after restarting using `lamachine-start-webserver`. I performed an upgrade of all of LaMachine, in the usual way, by re-running our Ansible installation playbook. I will now do a fresh re-install on one server.

It would however be nice if the webservice also upgrades using an upgrade. Which files did you change? Maybe it is caused by our Ansible script, since we also copy picclservice.py files from a template.

**Comment by proycon** [comment]
Ah! right, that must be it, ``picclservice.py`` changed (and may in the future too). I didn't realize you weren't using the supplied version but your own.

**Comment by proycon** [comment]
(with the new CLAM 2.3 and the external yaml configuration files, keeping  your own copy of the service configuration script ``picclservice.py`` shouldn't be necessary anymore by the way,; custom host-specific configuration can go in the yaml file that is dynamically included from the service configuration script)

**Comment by pdekker12** [comment]
I got the debug mode working and gathered some output, this is quite striking:
```
LANG=C
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=
```
I never saw C in any of ther other locale commands I issued on my system. Eg. if I issue `locale` as the piccl user, I get:
```
LANG=nl_NL.UTF-8
LC_CTYPE="nl_NL.UTF-8"
LC_NUMERIC="nl_NL.UTF-8"
LC_TIME="nl_NL.UTF-8"
LC_COLLATE="nl_NL.UTF-8"
LC_MONETARY="nl_NL.UTF-8"
LC_MESSAGES="nl_NL.UTF-8"
LC_PAPER="nl_NL.UTF-8"
LC_NAME="nl_NL.UTF-8"
LC_ADDRESS="nl_NL.UTF-8"
LC_TELEPHONE="nl_NL.UTF-8"
LC_MEASUREMENT="nl_NL.UTF-8"
LC_IDENTIFICATION="nl_NL.UTF-8"
LC_ALL=
```

**Comment by kosloot** [comment]
O, 'C' is certainly the last thing you want. Indeed strange WHY this happen. Maybe it runs in a shell and doesn't source .bashrc or the like? Lots of possible problems.
But the webservice script sets the local now, so why isn't that working?

**Comment by proycon** [comment]
Hmm, that means forcing the local from the wrapper script and from the ``lamachine-start-webserver`` script both didn't work, which is a bit puzzling. It's not entirely unexpected that it's not your usual locale because uwsgi does probably spawn a non-interactive shell which might bypass your usual interactive shell configuration. If you can't force the locale system-wide, then perhaps we should try setting the locale in the uwsgi vassal script. What happens if you add the following to your ``piccl.ini`` (in ``etc/uwsgi-emperor`` and rerun ``lamachine-start-webserver``?

``env = LC_ALL=en_US.UTF-8``

**Comment by pdekker12** [comment]
I tried your suggestion, however it still fails, and the debug output contains the C locale

BTW: `lamachine-start-webserver` keeps running (I expected it to be just a startup script), and keeps periodically outputting the following:
https://pastebin.ubuntu.com/p/yjfPHXcpS8/

**Comment by proycon** [comment]
> I tried your suggestion, however it still fails, and the debug output contains the C locale

I didn't expect it to be so stubborn.. we've tried quite some places already. I don't really know CentOS well and it doesn't replicate here on debian/ubuntu or arch, but it's as if something actively resets the locale. Does ``~/.bash_profile`` , ``~/.profile`` or ``~/.bashrc`` set a local, is there anything in ``/etc/environment`` or /etc/profile``? I could force a locale in the LaMachine activation script as well, though I don't really want to force a particular locale on users (as long as it's a proper UTF-8 one and not C).

> BTW: lamachine-start-webserver keeps running (I expected it to be just a startup script), and keeps periodically outputting the following:
https://pastebin.ubuntu.com/p/yjfPHXcpS8/

It does detach but processes like the  uwsgi emperor indeed still write to stderr/stdout. This output (even the weird module errors, look normal, and should pose no problems)

**Comment by pdekker12** [comment]
One issue I could still think of, is the fact that the locale is called "en_US-utf8" in CentOS, while you hardcode it in picclservice_wrapper.py as "en_US.UTF-8". I will try to change it

**Comment by pdekker12** [comment]
I seem to have solved the problem. It had to do with our configuration, my apologies for all the hassle. In our installation, a template file is copied to `/etc/sysconfig/httpd` which contained the option `LANG=C` :( According to the comments, this was added for compatibility with certain Apache modules, but it has for now mainly caused trouble...

**Comment by proycon** [comment]
I'm glad you managed to find it ;) Such tiny bugs can hide in small corners..

> One issue I could still think of, is the fact that the locale is called "en_US-utf8" in CentOS, while you hardcode it in picclservice_wrapper.py as "en_US.UTF-8". 

Really? that looks very weird to me, I've always seen pretty consistent locale names everywhere..
